---
plugin: excel_inventory

source_type: local
sheet_name: "ORACLE"

local_config:
  file_path: "bases_de_datos/ansible-checklist-databases/inventory/InventarioBD.xlsx"

hostname_column: "Instancia"

compose:
  ansible_host: "Direccion_IP"
  oracle_databases_port: 1531
  server_name: "Host"
  ambiente: "Ambiente"

keyed_groups:
  - key: Host

groups:
  oracle_dbs_prod: "Ambiente == 'Producción'"
  oracle_dbs_desa: "Ambiente == 'Desarrollo'"
  oracle_dbs_labo: "Ambiente == 'Laboratorio'"
  oracle_dbs_stagin: "Ambiente == 'Staging'"
