---
# Configuración global Oracle
oracle_timeout: 60

# Inventario simplificado de bases de datos
oracle_databases:
  dbMayus1:
    # Datos de conexión
    instancia: "dbMayus1"
    host: "oracle7db"
    direccion_ip: "192.168.20.230"
    cadena_tns: "dbMayus1"
    usuario: "ansible_user"
    password: "ansibledb123*"
    puerto: 1521
    # Metadatos para reporte
    motor_bd: "Oracle"
    sistema_operativo: "Red Hat Enterprise Linux Server"
    release_so: "8.x"
    release_bd: "19.0.0.0"

  dbprueba:
    instancia: "dbprueba"
    host: "oracle7db"
    direccion_ip: "192.168.20.230"
    cadena_tns: "dbprueba"
    usuario: "ansible_user"
    password: "ansibledb123*"
    puerto: 1521
    motor_bd: "Oracle"
    sistema_operativo: "Red Hat Enterprise Linux Server"
    release_so: "8.x"
    release_bd: "19.0.0.0"

  PRUEBA:
    instancia: "PRUEBA"
    host: "oracle7db"
    direccion_ip: "192.168.20.230"
    cadena_tns: "PRUEBA"
    usuario: "ansible_user"
    password: "ansibledb123*"
    puerto: 1521
    motor_bd: "Oracle"
    sistema_operativo: "Red Hat Enterprise Linux Server"
    release_so: "8.x"
    release_bd: "19.0.0.0"

  dbotro:
    instancia: "dbotro"
    host: "oracle7db"
    direccion_ip: "192.168.20.230"
    cadena_tns: "dbotro"
    usuario: "ansible_user"
    password: "ansibledb123*"
    puerto: 1521
    motor_bd: "Oracle"
    sistema_operativo: "Red Hat Enterprise Linux Server"
    release_so: "8.x"
    release_bd: "19.0.0.0"